/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasV2;

import CRUD_Classes.DatePicker;
import Conection.Conexion;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author propietario
 */
public class DeductionForm extends javax.swing.JFrame {

    /**
     * Creates new form sickleaveForm
     */
    boolean update;
    int emp_no;
    Date date;
    public DeductionForm() {
        initComponents();
    }
    
    public DeductionForm(JTable j, int linea){
        initComponents();
        llenar(j, linea);
        this.update = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee no. :");

        jTextField1.setToolTipText("Ej: 10001");

        jButton2.setText("Set Date");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("deduct_date");

        jLabel3.setText("deduct_amount");

        jLabel4.setText("deduct_type_no");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Deduction Formulario");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Puntualidad", "Aguinaldo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1)
                                        .addComponent(jTextField2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(update){
        if (jTextField1.getText().equals("") || jTextField2.getText().equals(""))  {
                          JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
                
                }
     
               else{
                    Conexion con = new Conexion();
                    Connection c = con.miconexion(2);
                   DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                   String fecha1 = jButton2.getText();
                   String fecha2 = date.toString();
                    int amount = Integer.parseInt(jTextField2.getText());
                    int n = jComboBox1.getSelectedIndex()+1;
                    LocalDate localDate = LocalDate.parse(fecha1, formatter);
                    LocalDate localDate2 = LocalDate.parse(fecha2, formatter);
                    java.sql.Date sqlDate = java.sql.Date.valueOf( localDate );
                    java.sql.Date sqlDate2 = java.sql.Date.valueOf( localDate2 );
                    if (c != null) {
                    

                    try {
                    Statement st = c.createStatement();
                     PreparedStatement pstmt = c.prepareStatement("UPDATE meni.deduction SET emp_no = ?, deduct_date = "
                             + "?, deduct_amount = ?, deduct_type_no = ?"
                             +"WHERE emp_no =? AND deduct_date = ?");
                     
                      pstmt.setInt(1, Integer.parseInt(jTextField1.getText()));
                      pstmt.setDate(2, sqlDate);
                      pstmt.setInt(3, amount);
                      pstmt.setInt(4, n);
                      pstmt.setInt(5, emp_no);
                      pstmt.setDate(6, sqlDate2);
                     pstmt.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null, "Dato agregado correctamente xD");
                    this.dispose();
                    jTextField1.setText("");
                    c.commit();
                    c.close();
//                    field8.setText("");
                     } catch(SQLException se10) {
                    JOptionPane.showMessageDialog(null, se10);
                    }
                       
                     
                }
        }
        }else{
            if (jTextField1.getText().equals(""))  {
                          JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
                
                }else if(jTextField2.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
                }else if (jButton2.getText().equals("")||jButton2.getText().equals("Set Date")||jButton2.getText().equals("Set Date")){
                    JOptionPane.showMessageDialog(null, "Hay que seleccionar una fecha");
                }else{
            Conexion con = new Conexion();
                    Connection c = con.miconexion(2);
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                    
                    int nuevoid = Integer.parseInt(jTextField1.getText());
                    String fecha1 = jButton2.getText();
                    
                    LocalDate localDate = LocalDate.parse(fecha1, formatter);
                    
                    java.sql.Date sqlDate = java.sql.Date.valueOf( localDate );
                    
                    int amount = Integer.parseInt(jTextField2.getText());
                    int n = jComboBox1.getSelectedIndex()+1;
                    if (c != null) {
                    

                    try {
                      
                      Statement st = c.createStatement();
                     PreparedStatement pstmt = c.prepareStatement("INSERT INTO meni.deduction VALUES (?,?,?,?)");
                      pstmt.setInt(1, nuevoid);
                      pstmt.setDate(2, sqlDate);
                      pstmt.setInt(3, amount);
                      pstmt.setInt(4, n);
                     
                      
                      pstmt.executeUpdate();
                      c.commit();
                    c.close();
                    JOptionPane.showMessageDialog(null, "Dato agregado correctamente xD");
                    this.dispose();
                    }catch(Exception e){
                        System.out.println(e);
                        JOptionPane.showMessageDialog(null, e);
                    }
                    }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JPanel p = new JPanel();
        
		final JFrame f = new JFrame();
                f.setLocationRelativeTo(jButton2);
		f.getContentPane().add(p);
		f.pack();
		f.setVisible(true);
                jButton2.setText(new DatePicker(f).setPickedDate());
                               
                                f.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeductionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeductionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeductionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeductionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeductionForm().setVisible(true);
            }
        });
    }
    public void llenar(JTable j, int linea){
        jTextField1.setText(j.getValueAt(linea, 0).toString());
        this.emp_no = Integer.parseInt(jTextField1.getText());
        jButton2.setText(j.getValueAt(linea, 2).toString());
        this.date = Date.valueOf(jButton2.getText());
        jTextField2.setText(j.getValueAt(linea, 3).toString());
        jComboBox1.setSelectedIndex(Integer.parseInt(j.getValueAt(linea, 4).toString())-1);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
